merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name="band-list"),
    path('bands/<int:band_id>/', views.band_detail, name="band-detail"),
    path('bands/create/', views.band_create, name="band-create"),
    path('bands/<int:band_id>/update/', views.band_update, name="band-update"),
    path('bands/<int:band_id>/delete/', views.band_delete, name="band-delete"),
    path('about-us/', views.about),
    path('listings/', views.listing_list, name="listing-list"),
    path('listings/<int:listing_id>', views.listing_detail, name="listing-detail"),
    path('listings/create/', views.listing_create, name="listing-create"),
    path('listings/<int:listing_id>/update/', views.listing_update, name="listing-update"),
    path('contact-us/', views.contact, name="contact"),
    path('email-sent/', views.email_sent, name="email-sent"),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
    
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2022)])
    active = models.fields.BooleanField(default=True)
    official_page = models.fields.URLField(null=True, blank=True)
    # like_new = models.fields.BooleanField(default=False)

    def __str__(self):
        return self.name
    

class Listing(models.Model):

    class Type(models.TextChoices):
        RECORDS = 'RECORDS'
        CLOTHING = 'CLOTING'
        POSTERS = 'POSTERS'
        MISCELLANEOUS = 'MISCELLANEOUS'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True)
    type = models.fields.CharField(choices=Type.choices, max_length=50)

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title
    

merchex/listings/forms.py
from django import forms

from listings.models import Band, Listing

class ContactForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = '__all__'

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

merchex/listings/views.py
from django.http import HttpResponse, HttpRequest
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from listings.models import Band, Listing
from listings.forms import ContactForm, BandForm, ListingForm

# Create your views here.


def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)
    return render(request, 'listings/band_detail.html', {"band": band})

def band_create(request: HttpRequest):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if(form.is_valid()):
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request, 'listings/band_create.html', {"form": form})

def band_update(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if(form.is_valid()):
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)
    return render(request, 'listings/band_update.html', {'form': form})

def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)

    if request.method == 'POST':
        band.delete()
        return redirect('band-list')
    return render(request, 'listings/band_delete.html', {'band': band})

def about(request):
    return render(request, 'listings/about.html')


def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'listings': listings})


def listing_detail(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    return render(request, 'listings/listing_detail.html', {'listing': listing})

def listing_create(request: HttpRequest):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()
    return render(request, 'listings/listing_create.html', {'form': form})
    
def listing_update(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if(form.is_valid()):
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request, 'listings/band_update.html', {'form': form})    

def email_sent(request):
    return render(request, 'listings/email_sent.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email-sent')
    else:
        form = ContactForm()
    return render(request, 'listings/contact.html', {'form': form})

merchex/listings/templates/listings/about.html
{% extends "listings/base.html" %}


{% block content %}
    <h1>About</h1>
{% endblock content %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %} 
{% block content %}

    <h1>Créer un nouveau groupe</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer" />
    </form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %} 
{% block content %}

    <h1>Supprimer le groupe</h1>
    <p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
    </form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends "listings/base.html" %}

{% block content %}
    <h2>{{ band.name }}</h2>

    <ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    <li><a href="{{band.official_page}}">{{ band.official_page }}</a></li>
    </ul>

    <p>{{ band.biography }}</p>

    <a href="{% url 'band-update' band.id %}">Modifier le groupe</a>
    <a href="{% url 'band-list' %}">Retour à tous les groupes</a>

    <ul>
        {% for listing in band.listing_set.all %}
            <li><a href="{% url 'listing-detail' listing.id %}">{{listing.title}}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends "listings/base.html" %} {% block content %}
<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
<h1>Hello Django !</h1>
<p>J'ai {{bands|length}} groupes preferes</p>

<ul>
  {% for band in bands %}
  <li>
    <a href=" {% url 'band-detail' band.id %} ">{{ band.name|upper }}</a>----
    <a href=" {% url 'band-update' band.id %} ">Modifier</a>----
    <a href=" {% url 'band-delete' band.id %} ">Supprimer</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %} 
{% block content %}

    <h1>Modifier un groupe</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer" />
    </form>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <title>Merchex</title>
  </head>
  <body>
    <nav>
      <a href="{% url 'band-list' %}">Groupes</a>
      <a href="{% url 'listing-list' %}">Annonces</a>
      <a href="{% url 'contact' %}">Contact</a>
    </nav>
    {% block content %} {% endblock %}
  </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends "listings/base.html" %}

{% block content %}
    <h1>Contact</h1>
{% endblock content %}

merchex/listings/templates/listings/email_sent.html
{% extends "listings/base.html" %}

{% block content %}
    <p>Mail envoyé avec succès</p>
{% endblock content %}

merchex/listings/templates/listings/listing_create.html
{% extends "listings/base.html" %}

{% block content %}
    <h1>Créer une nouvelle annonce</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer" />
    </form>
{% endblock content %}

merchex/listings/templates/listings/listing_detail.html
{% extends "listings/base.html" %}

{% block content %}
    <h2>{{ listing.title }}</h2>

    <ul>
        <li>Titre : {{ listing.title }}</li>
        <li>Type : {{ listing.get_type_display }}</li>
        <li>Année : {{ listing.year }}</li>
        <li>Sold : {{ listing.sold|yesno }}</li>
    </ul>

    <p>{{ listing.description }}</p>

    <a href="{% url 'listing-update' listing.id %}">Modifier l'annonce</a>
    <a href="{% url 'listing-list' %}">Retour à tous les anonces</a>
    
{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends "listings/base.html" %}

{% block content %}
    <a href="{% url 'listing-create' %}">Créer une nouvelle annonce</a>
    <h1>La liste de toutes les annonces</h1>
    {% for listing in listings %}
        <li><a href=" {% url 'listing-detail' listing.id %} ">{{ listing.title|upper }}</a>----<a href=" {% url 'listing-update' listing.id %} ">Modifier</a></li>
    {% endfor %}
    </ul>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends "listings/base.html" %}

{% block content %}
    <h1>Modifier une annonce</h1>

    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer" />
    </form>
{% endblock content %}

merchex/listings/templates/listings/listings.html
{% extends "listings/base.html" %}

{% block content %}
    <h1>Listings</h1>
    <ul>
        {% for listing in listings  %}
            <li>{{ listing.title }}</li>
        {% endfor %}
    </ul>
{% endblock content %}